### ISSUE TITLE
Include commands in command palette

### ISSUE THREAD

**Issue by rchl** [tushortz/LangDocs#2]
As there is a lot of commands and the shortcuts might be hard to remember, it would be nice if the plugin would add all supported commands to command palette (ctrl+shift+p menu).

**Comment by tushortz** [comment]
Thanks for the suggestion. At the moment I'm piled up with course works so
an update might be around next month. I'll also need to go through the
sublime text documentation to understand how that works.

:) but I wouldn't mind being helped though.

**Comment by rchl** [comment]
Sure, might try to help if I find time myself.

**Comment by rchl** [comment]
BTW. Docs: http://docs.sublimetext.info/en/latest/reference/command_palette.html

**Comment by tushortz** [comment]
Done
